### ISSUE TITLE
Breaking Change in Release 6

### ISSUE THREAD

**Issue by edubsi** [FantasticFiasco/serilog-sinks-udp#55]
First thank you for the library which is very useful for me.

This is a suggesting for the upgrade path to Release 6 and not a bug report.
The upgrade to version 6 broke our logging to UDP and thankfully the breaking changes very documented very well in the release notes.

I was wondering if a fallback to the old behavior is possible -> if the configuration is not available assume IPv4/"family": "InterNetwork".  This way it would not break the unchanged configs and allow the switch to IPv6 if needed.

Other than that adding the documented change fixed logs for me.

**Comment by FantasticFiasco** [comment]
Hi and welcome to this repository!

You are correct that v6.0.0 introduced breaking changes, and those changes probably affected all consumers of the NuGet package. I'm trying to limit the amount of breaking changes I introduce, but sometimes they are unavoidable.

The NuGet package is following Semantic versioning, as documented in [CHANGELOG.md](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/CHANGELOG.md), and any update to the major version is indicating a breaking change. I would happily accept proposals to other means of letting the consumers know that a major version update is indicating a breaking change.

v6.0.0 was not my best release, I will agree to that. It fixed a problem introduced in v5.0.0, based on my assumption that networks nowadays all supported IPv6. That was clearly wrong. So release v6.0.0 is actually a fix for something I started in v5.0.0, and we will probably not see any more breaking changes when it comes to IP versioning (crossing my fingers).

Please let me know if there are aspects of your issue that are still unanswered, otherwise you can close the issue. Please accept my humble apology for the breaking changes, and continue to enjoy the fantastic Serilog.
